apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-med-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-med-api
  template:
    metadata:
      labels:
        app: health-med-api
    spec:
      containers:
        - name: health-med-api
          image: fabianogoes/health-med-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
          envFrom:
            - secretRef:
                name: health-med-secret
          env:
            - name: POSTGRES_HOST
              value: health-med-db.cixfuebhftfn.us-east-1.rds.amazonaws.com
            - name: POSTGRES_DB
              value: health_med_db
            - name: POSTGRES_USERNAME
              value: health_med_usr
            - name: POSTGRES_PASSWORD
              value: health_med_pwd
            - name: JWT_KEY
              value: 3cafe40f92be6ac77d2792b4b267c2da11e3f3087b93bb19c6c5133786984b44
            - name: MAIL_PASSWORD
              value: guom rkou rwcu dkju
            - name: MAIL_USERNAME
              value: fabianogoes@gmail.com
            - name: AWS_REGION
              value: us-east-1
            - name: POSTGRES_PORT
              value: "5432"
            - name: APP_NAME
              value: health-med-api
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: ":8080"
            - name: API_VERSION
              value: "1.0"
      restartPolicy: Always
