apiVersion: v1
kind: Service
metadata:
  name: health-med-api
  labels:
    app: health-med-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: health-med-api
