name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Grant execute permissions
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew test

  build:    
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: write
      attestations: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto' 
    - name: Grant execute permissions
      run: chmod +x gradlew        
    - name: Build
      run: ./gradlew build      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image:$GITHUB_SHA
    - name: Log in to the Docker registry
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/my-image:$GITHUB_SHA
