name: CI

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: health-med-api:latest
  JAR_PATH: app/build/libs/app-0.0.1-SNAPSHOT.jar

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Grant execute permissions
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew test

  coverage:
    runs-on: ubuntu-latest
#    needs: test
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew clean jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

  build:    
    runs-on: ubuntu-latest
    needs: coverage
    permissions:
      packages: write
      contents: write
      attestations: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto' 
      
    - name: Cache the artifact
      uses: actions/cache@v3
      with:
        path: ${{ env.JAR_PATH }}
        key: ${{ runner.os }}-java-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-java-        
          
    - name: Grant execute permissions
      run: chmod +x gradlew        
    - name: Build
      run: ./gradlew build

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached artifact
        uses: actions/cache@v3
        with:
          path: ${{ env.JAR_PATH }}
          key: ${{ runner.os }}-java-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-java-

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}
