name: CI

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: health-med-api:latest
  JAR_PATH: app/build/libs/app-0.0.1-SNAPSHOT.jar

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Restore cached artifact
        uses: actions/cache@v3
        with:
          path: ${{ env.JAR_PATH }}
          key: ${{ runner.os }}-java-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-java-
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew clean jacocoTestReport

      - name: jacoco-badge-generator-schedule
        id: jacocoModSchedule
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: schedule/build/reports/jacoco/test/jacocoTestReport.csv
          coverage-badge-filename: jacoco-schedule.svg
          branches-badge-filename: branches-schedule.svg
          coverage-label: Coverage module Schedule [Use Cases]
          workflow-summary-heading: Module Schedule JaCoCo Test Coverage Summary

      - name: jacoco-badge-generator-doctor
        id: jacocoModDoctor
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: doctor/build/reports/jacoco/test/jacocoTestReport.csv
          coverage-badge-filename: jacoco-doctor.svg
          branches-badge-filename: branches-doctor.svg
          coverage-label: Coverage module Doctor [Use Cases]
          workflow-summary-heading: Module Doctor JaCoCo Test Coverage Summary

      - name: jacoco-badge-generator-patient
        id: jacocoModPatient
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: patient/build/reports/jacoco/test/jacocoTestReport.csv
          coverage-badge-filename: jacoco-patient.svg
          branches-badge-filename: branches-patient.svg
          coverage-label: Coverage module Patient [Use Cases]
          workflow-summary-heading: Module Patient JaCoCo Test Coverage Summary

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"      

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report - Schedule
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-schedule
          path: schedule/build/reports/jacoco/

      - name: Upload JaCoCo coverage report - Doctor
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-doctor
          path: doctor/build/reports/jacoco/

      - name: Upload JaCoCo coverage report - Patient
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-patient
          path: patient/build/reports/jacoco/

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60


  build:    
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: write
      attestations: write
    steps:
    - uses: actions/checkout@v4
    - name: Restore cached artifact
      uses: actions/cache@v3
      with:
        path: ${{ env.JAR_PATH }}
        key: ${{ runner.os }}-java-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-java-
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto' 
      
    - name: Cache the artifact
      uses: actions/cache@v3
      with:
        path: ${{ env.JAR_PATH }}
        key: ${{ runner.os }}-java-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-java-        
          
    - name: Grant execute permissions
      run: chmod +x gradlew        
    - name: Build
      run: ./gradlew build

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached artifact
        uses: actions/cache@v3
        with:
          path: ${{ env.JAR_PATH }}
          key: ${{ runner.os }}-java-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-java-

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}
